{
 "title": "Chapter 3",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "µService",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://app-ex:3000/healthcheck\",job=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Downtime #",
   "type": "singlestat",
   "description": "Downtime counter",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "mttd",
     "query": "SELECT count(\"value\") FROM \"mtbf\" WHERE (\"app_name\" = 'app-ex') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "app_name", "operator": "=", "value": "app-ex" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((24 * 60 * 60) - sum(\"value\")) * 100 / (24 * 60 * 60)  FROM \"mtbf\" WHERE (\"app_name\" = 'app-ex') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MTTD",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mttd",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app_name", "operator": "=", "value": "app-ex" }
     ]
    }
   ]
  },
  {
   "title": "MTBF",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mtbf",
     "query": "SELECT ((2 * 24 * 60 * 60) - sum(\"value\")) / count(\"value\") FROM \"mtbf\" WHERE (\"app_name\" = 'app-ex') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "app_name", "operator": "=", "value": "app-ex" }
     ]
    }
   ]
  },
  {
   "title": "Up/Down Graph",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"http://app-ex:3000/healthcheck\",job=\"blackbox\"} > 0",
     "legendFormat": "up"
    },
    {
     "expr": "probe_success{instance=\"http://app-ex:3000/healthcheck\",job=\"blackbox\"} <= 0",
     "legendFormat": "down"
    }
   ]
  }
 ]
}